export { serializeLoginOutput } from './auth.serializer.js'
export { serializeStudent, serializePaginatedStudents } from './student.serializer.js'
export { serializeTeacher, serializePaginatedTeachers } from './teacher.serializer.js'
export { serializeSubject, serializePaginatedSubjects } from './subject.serializer.js'
export { serializeAcademicPeriod, serializePaginatedAcademicPeriods } from './academic-period.serializer.js'
export { serializeClassroom, serializePaginatedClassrooms } from './classroom.serializer.js'
export { serializeCourse, serializePaginatedCourses } from './course.serializer.js'
export { serializeEnrollment, serializePaginatedEnrollments } from './enrollment.serializer.js'
export { serializeGrade } from './grade.serializer.js'
export { serializeStudyPlan, serializePaginatedStudyPlans } from './study-plan.serializer.js'
export { serializeUser, serializePaginatedUsers } from './user.serializer.js'
export { serializeCourseGradeReport, serializeStudentAcademicHistory } from './report.serializer.js'
export { serializeTimetable } from './timetable.serializer.js'
