export type { LoginInput, LoginOutput, RegisterUserInput } from './auth.js'
export type { CreateStudentInput, UpdateStudentInput, StudentOutput, PaginatedOutput } from './student.js'
export type { CreateTeacherInput, UpdateTeacherInput, TeacherOutput } from './teacher.js'
export type { CreateSubjectInput, UpdateSubjectInput, SubjectOutput } from './subject.js'
export type { CreateAcademicPeriodInput, UpdateAcademicPeriodInput, AcademicPeriodOutput } from './academic-period.js'
export type { CreateClassroomInput, UpdateClassroomInput, ClassroomOutput } from './classroom.js'
export type { CreateCourseInput, UpdateCourseInput, CourseOutput } from './course.js'
export type { CreateEnrollmentInput, EnrollmentOutput } from './enrollment.js'
export type { CreateGradeInput, UpdateGradeInput, GradeOutput } from './grade.js'
export type { CreateStudyPlanInput, UpdateStudyPlanInput, StudyPlanOutput } from './study-plan.js'
export type { StudentAcademicHistoryOutput, CourseGradeReportOutput } from './report.js'
export type { UserOutput, UpdateUserInput } from './user.js'
export type { RegisterStudentInput, RefreshTokenOutput } from './auth.js'
